// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview A flow that suggests blog post titles based on trending keywords.
 *
 * - suggestBlogTitles - A function that suggests blog post titles.
 * - SuggestBlogTitlesInput - The input type for the suggestBlogTitles function.
 * - SuggestBlogTitlesOutput - The return type for the suggestBlogTitles function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestBlogTitlesInputSchema = z.object({
  keywords: z
    .string()
    .describe('The trending keywords to generate blog post titles from.'),
});
export type SuggestBlogTitlesInput = z.infer<typeof SuggestBlogTitlesInputSchema>;

const SuggestBlogTitlesOutputSchema = z.object({
  titles: z
    .array(z.string())
    .describe('An array of suggested blog post titles.'),
});
export type SuggestBlogTitlesOutput = z.infer<typeof SuggestBlogTitlesOutputSchema>;

export async function suggestBlogTitles(input: SuggestBlogTitlesInput): Promise<SuggestBlogTitlesOutput> {
  return suggestBlogTitlesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestBlogTitlesPrompt',
  input: {schema: SuggestBlogTitlesInputSchema},
  output: {schema: SuggestBlogTitlesOutputSchema},
  prompt: `You are a marketing expert. Generate 5 blog post titles based on the following trending keywords:\n\n{{keywords}}\n\nBlog Post Titles:`, config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const suggestBlogTitlesFlow = ai.defineFlow(
  {
    name: 'suggestBlogTitlesFlow',
    inputSchema: SuggestBlogTitlesInputSchema,
    outputSchema: SuggestBlogTitlesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
